### ISSUE TITLE
MissingPluginException when loading the theme.

### ISSUE THREAD

**Issue by jkoenig134** [Norbert515/dynamic_theme#42]
The shared-preferences plugin is currently only available for mobile. You could make this library usable for Desktop if you ask if the plugin is accessable before asking for shared preferences.
```
[ERROR:c:\b\s\w\ir\cache\builder\src\flutter\lib\ui\ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
#0      DynamicThemeState.loadBrightness (package:dynamic_theme/dynamic_theme.dart:84:37)
<asynchronous suspension>
#1      DynamicThemeState.initState (package:dynamic_theme/dynamic_theme.dart:46:5)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#6      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1142:16)
#7      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1113:5)
#8      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1055:17)
#9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
#10     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1054:13)
#11     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:935:7)
#12     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:917:7)
#13     _rootRun (dart:async/zone.dart:1129:38)
#14     _CustomZone.run (dart:async/zone.dart:1026:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:928:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:968:23)
#17     _rootRun (dart:async/zone.dart:1133:13)
#18     _CustomZone.run (dart:async/zone.dart:1026:19)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:952:23)
#20     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#21     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#22     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by marchacio** [comment]
This error is shown when the app has not yet fully loaded the new packages installed via `pubspec.yaml`.
Just close your app and debug again.

**Comment by jkoenig134** [comment]
@marchacio no, that´s because the plugin is not available for desktop.

**Comment by marchacio** [comment]
Ah, i didn't see, sorry. 
Usually it happends when the plugin was installed during debug
